import type { RewardLedgerEntry } from "@/features/engagement-retention/engagement-retention.types";

type RecentRewardLedgerProps = {
  rewards: RewardLedgerEntry[];
};

function formatDate(value: string) {
  return new Intl.DateTimeFormat("en-US", {
    dateStyle: "medium",
    timeStyle: "short",
  }).format(new Date(value));
}

function formatEventType(eventType: string) {
  return eventType
    .split("_")
    .map((word) => word[0]?.toUpperCase() + word.slice(1))
    .join(" ");
}

export function RecentRewardLedger({
  rewards,
}: RecentRewardLedgerProps) {
  return (
    <section className="rounded-[28px] border border-border/70 bg-card/90 p-6 shadow-[0_18px_60px_-50px_hsl(var(--primary)/0.55)]">
      <div>
        <p className="text-sm font-medium uppercase tracking-[0.22em] text-primary/70">
          Reward Ledger
        </p>

        <h2 className="mt-2 text-2xl font-semibold tracking-tight text-foreground">
          Recent Rewards
        </h2>

        <p className="mt-2 max-w-3xl text-muted-foreground">
          A transparent history of token rewards generated by focus, task
          completion, and streak milestones.
        </p>
      </div>

      {rewards.length === 0 ? (
        <div className="mt-6 rounded-[24px] border border-dashed border-border/70 p-8 text-center">
          <p className="text-sm text-muted-foreground">
            No reward events have been recorded yet.
          </p>
        </div>
      ) : (
        <div className="mt-6 space-y-3">
          {rewards.map((reward) => (
            <article
              key={reward.id}
              className="flex flex-col justify-between gap-3 rounded-[24px] border border-border/70 bg-secondary/25 p-4 md:flex-row md:items-center"
            >
              <div>
                <p className="font-semibold text-foreground">
                  {formatEventType(reward.event_type)}
                </p>
                <p className="mt-1 text-sm text-muted-foreground">
                  {reward.reward_note}
                </p>
                <p className="mt-1 text-xs text-muted-foreground/80">
                  {formatDate(reward.occurred_at)}
                </p>
              </div>

              <div className="rounded-full bg-amber-100 px-4 py-2 text-sm font-semibold text-amber-800">
                +{reward.token_delta} tokens
              </div>
            </article>
          ))}
        </div>
      )}
    </section>
  );
}