import type { AiInsightCardWithPrediction } from "@/features/ai-insights/ai-insight.types";
import { AiInsightCard } from "@/features/ai-insights/components/ai-insight-card";
import { GenerateDemoInsightButton } from "@/features/ai-insights/components/generate-demo-insight-button";

type AiInsightSectionProps = {
  cards: AiInsightCardWithPrediction[];
};

export function AiInsightSection({ cards }: AiInsightSectionProps) {
  return (
    <section className="space-y-5">
      <div className="flex flex-col justify-between gap-4 rounded-[28px] border border-border/70 bg-card/90 p-6 shadow-[0_18px_60px_-50px_hsl(var(--primary)/0.55)] md:flex-row md:items-center">
        <div>
          <p className="text-sm font-medium uppercase tracking-[0.22em] text-primary/70">
            Explainable AI
          </p>

          <h2 className="mt-2 text-2xl font-semibold tracking-tight text-foreground">
            AI Deadline Risk Insights
          </h2>

          <p className="mt-2 max-w-3xl text-muted-foreground">
            Demonstration cards generated by the deployed Deadline Risk model,
            SHAP explanations, and Gemini structured output generation.
          </p>
        </div>

        <GenerateDemoInsightButton />
      </div>

      {cards.length === 0 ? (
        <div className="rounded-[28px] border border-dashed border-border/70 bg-card/80 p-10 text-center">
          <h3 className="text-lg font-semibold text-foreground">
            No AI insight cards generated yet
          </h3>

          <p className="mt-2 text-sm text-muted-foreground">
            Generate a demo insight to validate the full ML → SHAP → Gemini
            pipeline inside the product UI.
          </p>
        </div>
      ) : (
        <div className="space-y-5">
          {cards.map((card) => (
            <AiInsightCard key={card.id} card={card} />
          ))}
        </div>
      )}
    </section>
  );
}